name: Tests

on:
  push:
    branches:
      - ci_pipeline

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      
      - name: view the secrets context
        shell: bash
        run: echo "${{ secrets.MYSECRET }}"
          
      - name: Test
        run: dotnet test
