name: Tests

on:
  push:
    branches:
      - ci_pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      
      - name: Test environment variables
        run: |
          echo "MYSECRET="${{ secrets.MYSECRET }}"" >> $GITHUB_ENV
          
          
      - name: Test
        run: dotnet test
