name: Tests

on:
  push:
    branches:
      - ci_pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      
      - name: Test environment variables
        run: |
          echo "MYSECRET="${{ secrets.MYSECRET }}"" >> $GITHUB_ENV
          echo "NEO4J_CONN="${{ secrets.NEO4J_CONN }}"" >> $GITHUB_ENV
          echo "NEO4J_USER="${{ secrets.NEO4J_USER }}"" >> $GITHUB_ENV
          echo "NEO4J_PASSWORD="${{ secrets.NEO4J_PASSWORD }}"" >> $GITHUB_ENV
          
      - name: Test
        run: dotnet test
