name: Build and Deploy

on:
  push:
    branches:
      - ci_pipeline

jobs:
  build:
    runs-on: windows-latest

    env:
      JWT_ISSUER: ${{ JWT_ISSUER }}
      JWT_AUDIENCE: ${{ JWT_AUDIENCE }}
      JWT_KEY: ${{ JWT_KEY }}
      MYSQL_READ: ${{ MYSQL_READ }}
      MYSQL_WRITE: ${{ MYSQL_WRITE }}
      MYSQL_READWRITE: ${{ MYSQL_READWRITE }}
      MYSQL_ADMIN: ${{ MYSQL_ADMIN }}
      MONGODB_CONN: ${{ MONGODB_CONN }}
      NEO4J_CONN: ${{ NEO4J_CONN }}
      NEO4J_USER: ${{ NEO4J_USER }}
      NEO4J_PASSWORD: ${{ NEO4J_PASSWORD }}
      NEO4J_DATABASE: ${{ NEO4J_DATABASE }}

    steps:
      - uses: actions/checkout@v2
        with:
           fetch-depth: 0

      - name: Build and Test
        run: |
          dotnet build
          dotnet test
