name: Tests

on:
  push:
    branches:
      - ci_pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      
      - name: Test environment variable
        run: |
          echo "MYSECRET=secret exposed" >> $GITHUB_ENV

          
      - name: Test
        run: dotnet test
