name: Tests

on:
  push:
    branches:
      - ci_pipeline

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      
      - name: Test environment variable
        run: |
          echo "MYSECRET=${{ secrets.MYSECRET }}" >> $GITHUB_ENV

          
      - name: Test
        run: dotnet test
